name: Terraform MultiK8s
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      # Terraform action to perform
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_Apply
        - Terraform_Destroy

env:
  SHA: $(git rev-parse HEAD)

jobs:
  Multi-cluster-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SCRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      ########################## EKS ##########################
      - name: EKS Deploy
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        run: |-   
          cd 01-ekscluster-terraform-manifests
          terraform init
          terraform apply --auto-approve  

      - name: EKS Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        run: |-   
          cd 01-ekscluster-terraform-manifests
          terraform init
          terraform destroy --auto-approve