name: Terraform MultiK8s
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      # Terraform action to perform
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_Apply
        - Terraform_Destroy

env:
  SHA: $(git rev-parse HEAD)

jobs:
  Multi-cluster-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1

      ########################## EKS ##########################
      - name: EKS Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '01-ekscluster-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: EKS Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: EKS Apply
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '01-ekscluster-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      ####################### Autoscaler #######################
      - name: Autoscaler Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '02-cluster-autoscaler-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Autoscaler Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: Autoscaler Apply
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '02-cluster-autoscaler-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      ####################### CW Agent #######################
      - name: CWAgent Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '03-cloudwatchagent-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: CWAgent Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: CWAgent Apply
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '03-cloudwatchagent-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   

      ####################### Ingress #######################
      - name: Ingress Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '04-nginx-ingress-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Ingress Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: Ingress Apply
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '04-nginx-ingress-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1        

      ####################### RDS #######################
      - name: RDS Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '05-rds-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1 

      - name: RDS Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: RDS Apply
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '05-rds-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1    
        with:
          args: -var="rds_password=$secrets.PG_PASSWORD"

      ####################### Redis #######################
      - name: RDS Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '06-redis-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1 

      - name: RDS Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: RDS Apply
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '06-redis-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1      

      ####################### EKS APP #######################
      - name: EKS App Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '07-eks-fibonacci-calculator-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1 

      - name: EKS App Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      - name: EKS App Apply
        if: ${{ github.event.inputs.action == 'Terraform_Apply' || github.event.inputs.action == ''}}
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '07-eks-fibonacci-calculator-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1         

      - name: Get Ingress URL
      # Get EKS Ingress Service URL
        run: |-   
          aws eks update-kubeconfig --region us-east-1 --name multi-k8s-terraform
          kubectl get services

      ########################## DESTROY #############################

      - name: EKS App Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '07-eks-fibonacci-calculator-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   
        run: |-   
          cd 07-eks-fibonacci-calculator-manifests
          terraform init
          terraform destroy --auto-approve

      - name: Redis Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '06-redis-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   
        run: |-   
          cd 06-redis-terraform-manifests
          terraform init
          terraform destroy --auto-approve   

      - name: RDS Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '05-rds-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   
        run: |-   
          cd 05-rds-terraform-manifests
          terraform init
          terraform destroy --auto-approve -var="rds_password=$secrets.PG_PASSWORD"

      - name: Ingress Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '04-nginx-ingress-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   
        run: |-   
          cd 04-nginx-ingress-terraform-manifests
          terraform init
          terraform destroy --auto-approve 

      - name: CWAgent Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '03-cloudwatchagent-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   
        run: |-   
          cd 03-cloudwatchagent-terraform-manifests
          terraform init
          terraform destroy --auto-approve 

      - name: Autoscaler Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '02-cluster-autoscaler-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   
        run: |-   
          cd 02-cluster-autoscaler-terraform-manifests
          terraform init
          terraform destroy --auto-approve

      - name: EKS Destroy
        if: ${{ github.event.inputs.action == 'Terraform_Destroy'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '01-ekscluster-terraform-manifests'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1   
        run: |-   
          cd 01-ekscluster-terraform-manifests
          terraform init
          terraform destroy --auto-approve